### ISSUE TITLE
FAT partition for /boot is waste of space

### ISSUE THREAD

**Issue by MaikStohn** [ayufan-pine64/linux-build#24]
I made a serial cable for my pinebook today and activated serial output permanently with internal switch.

The U-BOOT load can be interrupted by pressing the "s" key.

Then I found that "ext4load" is available.

==> Suggestion: 
We can shrink the fat partition to just some MB and load the kernel and bootlogo with ext4load instead of fatload.

Now the 100 MB FAT partition looks a bit of waste.

**Comment by ayufan** [comment]
It depends. The FAT partition makes an easily accessible configuration. This is why it is fat, and not ext4.

**Comment by MaikStohn** [comment]
Do you mean "more easy to access for users with other OS on other machine"?
Also the SD card would benefit from this idea but the eMMC most likely not.

Since most users will use the SD-IMAGE tool to completely write the SD card with a complete image I do not see the point of easy access. Anybody else for sure can mount an ext4 same way as FAT partition.

**Comment by ayufan** [comment]
Right for eMMC. However, this doesn't sense to differentiate between different builds, as this is more maintenance problem: the wasted space is about 60-70MB, which is 0.3% of total storage.

**Comment by pfeerick** [comment]
I agree, it isn't worth hosting a separate eMMC only copy of every version of the pinebook images just for an up to 70MB space saving. The /boot partition should remain FAT so it can be easily edited, and unfortunately needs to be at absolute minimum 70MB in size in order to not trigger the stupid "Software Updater" free space issue, as not everyone will be using linux to create their microSD, and beginners don't need the extra hassle of loading specialised software and drivers just to edit the uEnv.txt file. Setting it at 100MB prevents any issues if files get bigger or people start fiddling with stuff in the /boot partition... i.e. keeping a backup copy of stuff while testing alternate versions, etc. I do get your point, that it seems like a waste of space on the eMMC... but you are quite welcome to fork the build system and modify if you want different behaviour! :-O
