### ISSUE TITLE
[v0.7.5] Suspend-resume is broken

### ISSUE THREAD

**Issue by Funmungus** [ayufan-pine64/linux-build#39]
Using Pinebook with default Mate desktop, starting from fresh 0.6.2 installation

Symptoms:
1) Closing laptop lid or suspend from the shutdown menu will put the Pinebook to sleep, but only wake to a black screen.
2) `sudo systemctl suspend` does not successfully suspend, and will be a black screen.  This was only tried once, and may be a fluke.

Steps to reproduce:
1) Start with Pinebook v0.6.2 firmware
2) Use the following scripts from /usr/local/sbin
 * sudo ./pine64_update_kernel.sh 0.7.5
 * sudo ./pine64_update_uboot.sh 0.7.5
 * sudo ./pine64_update_package.sh 0.7.5
3) Possible steps that may not be required to reproduce
 * sudo ./pine64_update_kernel.sh 0.7.7
 * sudo ./pine64_update_package.sh 0.7.7
 * Install Mali support from https://launchpad.net/%7Eayufan/+archive/ubuntu/pine64-ppa/ and finish install with /usr/local/sbin/pine64_enable_sunxidrm.sh
4) Attempt to suspend

Workaround:
1) Downgrade firmware with the following scripts from /usr/local/sbin
 * sudo ./pine64_update_kernel.sh 0.6.2
 * sudo ./pine64_update_uboot.sh 0.6.2
 * sudo ./pine64_update_package.sh 0.6.2

**Comment by Funmungus** [comment]
So I have downgraded after installing sunxi libraries.  Will sunxi, Mali, and egl still work, or is a newer kernel build required?

**Comment by pfeerick** [comment]
`0.6.2` is the current 'stable' release... whereas `0.7.x` are still pre-release, and hence buggy and instabilities are to be expected. For example, it's currently a 50/50 chance of the build suspending or locking up when you suspend (I've had both happen at one time or another before I disabled suspend), and then a 0% chance of it resuming... :-O the sunxi_drm is an experimental feature requiring the kernel changes in `0.7.x`, so it basically won't be working now since you've downgraded the kernel back down to `0.6.2`

**Comment by Funmungus** [comment]
I suspected as much.  I have not fully read the changes from stable to current. I would guess it has to do with the sunxi changes but I still see it with sunxi turned off

**Comment by ayufan** [comment]
DId you had suspend issue on sunxidrm or regular non egl drivers?

**Comment by Funmungus** [comment]
I tested both with sunxi installed and enabled and without.

**Comment by ayufan** [comment]
The https://github.com/ayufan-pine64/linux-build/releases/tag/0.7.10 can suspend when old DE driver is used. Suspend still does not work on `sunxidrm`.
