### ISSUE TITLE
apt update - deb.auyfan.eu 'Writing more data than expected'

### ISSUE THREAD

**Issue by luruke** [ayufan-pine64/linux-build#44]
I'm using `stretch-minimal-pinebook-bspkernel-0.7.10-105.img.xz`, running `apt update` I get this error:

![img_2582](https://user-images.githubusercontent.com/61326/29689867-052eb278-8925-11e7-8aa4-e8a52a1bf05e.jpg)

**Comment by pfeerick** [comment]
I think the Packages.gz has missed being compressed? I just tried downloading it, and it's a plain text file? 😕 Hence why it's four times bigger than expected! 😆 It also only lists up to v0.6.2... although that looks to related to 0.7.x still being pre-release? Since the package and packages go files appear to keep related to 'release'? https://github.com/ayufan/debian-repository

```
Package: linux-pine64-package
Version: 0.6.2
License: MIT
Vendor: Kamil Trzciński
Architecture: arm64
Maintainer: Kamil Trzciński <ayufan@ayufan.eu>
Installed-Size: 1238
Section: admin
Priority: optional
Homepage: https://gitlab.com/ayufan-pine64/linux-build
Description: Pine A64 Linux support package
MD5sum: 8928d6d3ad8095a9eba0607e7876e91b
SHA1: 1bdae32ac8f1ce0eaf85239edcccb1ed2d30a1e0
SHA256: 7c91653d07eba9972a2a98135aebbc04726f43690d52019dd433a866707530e5
SHA512: eb6ad17271455cf28f47720b2cbaf589965cadaba21c40ee28db9d73f00ac1aecc2942093ed8873673904300c40a9c772dbb7946603a7116e965a249c0644ea1
Filename: download/linux-build/0.6.2/linux-pine64-package-0.6.2.deb
Size: 947010
```

**Comment by ayufan** [comment]
It should be OK now.
